name = "dentalflo-chatbot-widget-v1"
compatibility_date = "2023-10-30"
main = "./.cloudflare/worker.js"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[site]
bucket = ".svelte-kit/cloudflare"

[env.production]
route = "*"

[env.staging]
route = "*"