name = "dentalflo-chatbot-widget"
main = "./.svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-03-19"

compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./.svelte-kit/cloudflare"

[build]
command = "npm run build"
