name = "dentalflo-chatbot-widget"
compatibility_date = "2025-03-19"

# For Pages deployments specifically
[build]
command = "npm run build"

[build.upload]
format = "directory"

# This is what Pages is looking for
[pages_build_output_dir]
value = ".svelte-kit/cloudflare"

[site]
bucket = ".svelte-kit/cloudflare"

[triggers]
crons = []

[vars]
# Define your environment variables here
# API_URL = "https://api.example.com"