name = "dentalflo-chatbot-widget"
main = "./.svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-03-19"

compatibility_flags = [
  "nodejs_compat",
  "streams_enable_constructors",
  "transformstream_enable_standard_constructor"
]

[site]
bucket = "./.svelte-kit/cloudflare"

[build]
command = "npm run build"
